name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run CI/CD Pipeline
        run: echo "CI/CD Pipeline executed successfully!"

      - name: Deploy
        run: echo "Application deployed successfully!"
